name: Build wine

on:
  push:
    branches: patch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:multilib-devel
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update
        run: |
          pacman -Sy
          echo -e 'MAKEFLAGS="-j4"' >> /etc/makepkg.conf
          echo -e 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          useradd -m builder
          chown builder . -R
          sudo -u builder -- gpg --import keys/pgp/*.asc
          pkgs=( $(sudo -u builder -- makepkg --packagelist) )

          echo ARTIFACT_VERSION=$(sh -c 'source ./PKGBUILD && echo $pkgver-$pkgrel') >> $GITHUB_ENV
          echo ARTIFACT_WINE_PATH=${pkgs[0]} >> $GITHUB_ENV
          echo ARTIFACT_WINE_NAME=$(basename ${pkgs[0]}) >> $GITHUB_ENV
          echo ARTIFACT_WINE_DEBUG_PATH=${pkgs[1]} >> $GITHUB_ENV
          echo ARTIFACT_WINE_DEBUG_NAME=$(basename ${pkgs[1]}) >> $GITHUB_ENV

      - name: Build
        run: |
          sudo -u builder -- makepkg -cfs --noconfirm

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.ARTIFACT_VERSION }}
          tag_name: v${{ env.ARTIFACT_VERSION }}

      - name: Upload Wine
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARTIFACT_WINE_PATH }}
          asset_name: ${{ env.ARTIFACT_WINE_NAME }}
          asset_content_type: application/zstd

      - name: Upload Wine Debug
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARTIFACT_WINE_DEBUG_PATH }}
          asset_name: ${{ env.ARTIFACT_WINE_DEBUG_NAME }}
          asset_content_type: application/zstd
